### ISSUE TITLE
Doesn't work on all screens

### ISSUE THREAD

**Issue by makalsky** [tsirkin/jira-rtl#4]
This extension renders it correctly in a full issue view (separate screen)
![image](https://user-images.githubusercontent.com/39026845/43044780-8c3e1afc-8db5-11e8-8ff1-5a372267868d.png)
But does not work in a popup screen that Jira uses now by default:
![image](https://user-images.githubusercontent.com/39026845/43044792-b4e7fb62-8db5-11e8-95aa-3cc6104c1973.png)

Will be glad to help if needed.
Thank you,

**Comment by tsirkin** [comment]
Just pushed the code 
Didn't touch the code for a while

**Comment by tsirkin** [comment]
Sorry for delay,
Just being very busy.

Look into https://github.com/tsirkin/jira-rtl/blob/master/app/scripts/rtl.js
rtlPage function .

Here I just use selectors to find bidi characters and either 
1. wrap them with bidi element
2. set the element direction
3. set alignment if needed.

Most likely it will be enough to inspect the element you need to rtl in the browser.
Find out what selector can be used for it.
Add the selector to array that is later fixed with bidi, alignment or direction.

Thanks!

**Comment by tsirkin** [comment]
Hi @makalsky 
I have released a new version of the plugin and it will be interesting to see if your issue is fixed.
I can't really check it myself as we are using on premise version of jira and you are seems to be with the cloud one.

Thanks

**Comment by LtrDan** [comment]
Just tried Jira Cloud - still doesn't work :\

Thanks, Dan

![Screen Shot 2019-03-07 at 1 31 17 PM](https://user-images.githubusercontent.com/10274719/54288864-d9ac0200-45b0-11e9-975a-8d8e8131f262.png)

**Comment by tsirkin** [comment]
Now, that's a problem 
I don't have a Jira Cloud access, this is a paid product and we have on premise installation
If somebody can get me inside I am willing to fix the issues

**Comment by LtrDan** [comment]
Actually there is 7 days free trial
https://www.atlassian.com/software/jira/try

Thanks

**Comment by dgoldm** [comment]
Hi @tsirkin, 
I noticed that all the texts that aren't displayed correctly are in <p> elements.
So I added "p" to the directionSelectors array in rtl.js - and your indispensable extension started working again!
I don't have any experience with pull requests. Should I try to create one, or could you make this tiny change yourself?

![Annotation 2019-06-07 074333](https://user-images.githubusercontent.com/11911957/59081669-047bcd00-88f8-11e9-810a-18935ddb3429.png)

**Comment by dgoldm** [comment]
Evgeny,
Any chance for this fix being applied in the near future?
In the meantime I'm distributing my fixed version to my team to install manually in Chrome's developer mode (and will gladly send it to anyone who requests it). But it would really be great to have it in the store.
Thanks again for this invaluable extension.
Dan

**Comment by tsirkin** [comment]
Sure thing,
Just was really busy, will do

**Comment by dgoldm** [comment]
Would you like me to add you to my team, so that you would have access to the cloud and could test it yourself? Or if it will take less of your time, I can test it for you.

**Comment by tsirkin** [comment]
Need some testing as changing direction of all "p" can be slow/break something

**Comment by tsirkin** [comment]
Just published a new version, it includes your proposition

https://github.com/tsirkin/jira-rtl/releases/tag/0.0.9
Hope it will resolve some issues

**Comment by dgoldm** [comment]
Is working great now.
Tested on screens where the previous version wasn't working:
1)
![enabled1](https://user-images.githubusercontent.com/11911957/60013061-2b6f2880-9686-11e9-8ad0-9bf2c74de61b.jpg)
2)
![enabled3](https://user-images.githubusercontent.com/11911957/60013065-2b6f2880-9686-11e9-9fb3-620c4a518aa1.jpg)
3)
![enabled2](https://user-images.githubusercontent.com/11911957/60013063-2b6f2880-9686-11e9-89f2-6993a4eca5c1.jpg)
Thanks!

**Comment by tsirkin** [comment]
Great.
Thanks , can you star the project by the way?
